# Generated by Django 3.2.3 on 2021-06-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210701_0151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
