# Generated by Django 3.2.3 on 2021-07-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_timestamp_post_publishing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Publishing_date',
            new_name='Publishing_Time',
        ),
    ]
