# Generated by Django 3.2.3 on 2021-07-10 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Publishing_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
