# Generated by Django 3.2.3 on 2021-11-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_remove_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='static/featured_image/%Y/%M/%D/'),
        ),
    ]
